#port: 6875

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVICE_FQDN_BOOKSTACK_6875
      - APP_URL=$SERVICE_FQDN_BOOKSTACK_6875
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=$SERVICE_USER_MARIADB
      - DB_PASS=$SERVICE_PASSWORD_MARIADB
      - DB_DATABASE=bookstack_db
    volumes:
      - '/path/to/bookstack_app_data:/config'
    ports:
      - '6875:80'
    restart: unless-stopped
    depends_on:
      - mariadb
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 2s
      timeout: 10s
      retries: 15
      
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=bookstack_db
      - MYSQL_USER=$SERVICE_USER_MARIADB
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_MARIADB
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
